In [33]:
import requests
import pandas as pd
import numpy as np
from urllib.request import urlopen, Request
from urllib.parse import urlencode
from bs4 import BeautifulSoup
import re

month,sector,yoy_chng,2y_chng,3y_chng
0,Employment Services,14.4,12.9,14.0
1,Information,9.5,3.4,7.4
2,Health Care and Social Assistance,5.2,1.2,5.1
3,"Professional, Scientific, and Technical Services",7.1,0.9,1.9
4,Transportation and Warehousing,13.3,-3.8,0.2
5,Administrative Services,10.1,-3.0,-1.7
6,Government,1.2,-3.5,-1.8
7,Finance and Insurance,0.6,-2.2,-1.9
8,Real Estate,1.7,-7.0,-6.5
9,Educational Services,1.2,-5.3,-6.9
10,Utilities,-1.0,-4.9,-8.3
11,Management of Companies and Enterprises,4.5,-5.2,-9.7
12,Wholesale Trade,5.1,-7.5,-10.0
13,Retail Trade,5.1,-10.6,-12.9
14,Construction,-2.0,-11.6,-13.3
15,Manufacturing,7.3,-11.2,-16.8
16,Accommodation and Food Services,45.5,-13.8,-19.0
17,"Arts, Entertainment, and Recreation",52.2,-18.3,-19.8